spring:
  data:
    redis:
      host: 3.39.34.103
      port: 6379
auth:
  jwt:
    issuer: team.sparta.com
    secret: ${JWT_SECRET}
    accessTokenExpirationHour: 168
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 500