spring:
  data:
    redis:
      host: 3.39.34.103
      port: 6379
auth:
  jwt:
    issuer: team.sparta.com
    secret: ${JWT_SECRET}
    accessTokenExpirationHour: 168
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 500
  h2:
    console:
      enabled: true # 콘솔을 enable 해야 H2 콘솔에 접근할 수 있다.
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
    username: sa
    password: 1234
auth:
  jwt:
    issuer: team.sparta.com
    secret: a123sadhuoi213sadoiuzxcio2137Asd
    accessTokenExpirationHour: 168